<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-05T16:42:32 IST" name="Default suite" finished-at="2023-07-05T16:42:47 IST" duration-ms="15583">
    <groups>
    </groups>
    <test started-at="2023-07-05T16:42:32 IST" name="Default test" finished-at="2023-07-05T16:42:47 IST" duration-ms="15583">
      <class name="generic_script1.Running">
        <test-method is-config="true" signature="open_appl()[pri:0, instance:generic_script1.Running@5d2a4eed]" started-at="2023-07-05T16:42:32 IST" name="open_appl" finished-at="2023-07-05T16:42:37 IST" duration-ms="5297" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_appl -->
        <test-method signature="run()[pri:0, instance:generic_script1.Running@5d2a4eed]" started-at="2023-07-05T16:42:37 IST" name="run" finished-at="2023-07-05T16:42:45 IST" duration-ms="8019" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Online] but found [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Online] but found [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at generic_script1.Running.run(Running.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method is-config="true" signature="close_appl(org.testng.ITestResult)[pri:0, instance:generic_script1.Running@5d2a4eed]" started-at="2023-07-05T16:42:45 IST" name="close_appl" finished-at="2023-07-05T16:42:47 IST" duration-ms="2180" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=run status=FAILURE method=Running.run()[pri:0, instance:generic_script1.Running@5d2a4eed] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_appl -->
      </class> <!-- generic_script1.Running -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
